import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import ThemeChanger from "@/components/DarkSwitch/DarkSwitch";
import Header from '@/components/Header/Header'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={"en"} suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
        <Header />
          <div>{children}</div>
          <ThemeChanger></ThemeChanger>
        </ThemeProvider>
      </body>
    </html>
  );
}

/*
este es es codigo solo para la configuracion de tailwind y next-themes, mas arriba esta ya con internazionalizacion
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div>{children}</div>
          <ThemeChanger></ThemeChanger>
        </ThemeProvider>
      </body>
    </html>
  );
}
  */
