
//Importaciones normales de next js
import type { Metadata } from "next";
import { Inter } from "next/font/google";

//Importaciones de componentes
import { Container } from "@/components/Container";
import Header from "@/components/Header/Header";
import ClientComponent from "@/components/ClientComponent";

//Importaciones de next internazionalization
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";


//PARA STATIC RENDERING de NEXT INTERNATIONALIZATION
// Can be imported from a shared config
import { locales } from "@/config";
import { unstable_setRequestLocale } from "next-intl/server";
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

//Manejo de fonts que viene desde create-react-app
const inter = Inter({ subsets: ["latin"] });

//La metadata de NEXT JS
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


//El async es parte de next int
export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  unstable_setRequestLocale(locale);
  const messages = await getMessages();
  return (
    
          <NextIntlClientProvider messages={messages}>
            
            <Container className="border-2 bg-blue-500 dark:bg-blue-900 border-sky-500 h-screen max-w-[1592px] max-h-[750px]">
              <div className="border-2 border-sky-500 h-full">
                <div>
                  <Header />
                  <ClientComponent locale={locale}></ClientComponent>
                  {children}
                  
                </div>
              </div>
            </Container>
            
          </NextIntlClientProvider>
        
  );
}